-- Code generated by protoc-gen-protorm. DO NOT EDIT.
-- versions:
-- 	protoc-gen-protorm (unknown)
-- 	protoc             (unknown)
-- source: embedded.proto
--
-- database: v1
-- schema:   embedded_v1
--
-- protorm — https://github.com/oh-tarnished/protorm

CREATE SCHEMA IF NOT EXISTS "embedded_v1";

-- Event exercises nested-message normalization: a singular message field becomes a belongs-to relation, a repeated message field becomes a has-many, while well-known and map fields stay scalar / JSONB.
CREATE TABLE "embedded_v1"."events" (
    -- Resource name; the AIP identifier.
    "name"  VARCHAR(255)  NOT NULL  PRIMARY KEY,
    -- Well-known type stays a scalar column, not a relation.
    "created"  TIMESTAMPTZ,
    -- Map fields stay JSONB.
    "labels"  JSONB,
    -- Foreign key to Location.
    "location_id"  VARCHAR(255)  NOT NULL,
    -- Foreign key to Location.
    "billing_id"  VARCHAR(255),
    CONSTRAINT "fk_events_location_id" FOREIGN KEY ("location_id") REFERENCES "embedded_v1"."locations"("id"),
    CONSTRAINT "fk_events_billing_id" FOREIGN KEY ("billing_id") REFERENCES "embedded_v1"."locations"("id")
);

-- Location is reachable from Event and so becomes its own table; its existing `id` field is promoted to the primary key.
CREATE TABLE "embedded_v1"."locations" (
    "id"  VARCHAR(255)  NOT NULL  PRIMARY KEY,
    "city"  VARCHAR(255)  NOT NULL,
    "venue"  VARCHAR(255)
);

-- Attendee carries an IDENTIFIER, so that field is its primary key.
CREATE TABLE "embedded_v1"."attendees" (
    "name"  VARCHAR(255)  NOT NULL  PRIMARY KEY,
    "email"  VARCHAR(255)  NOT NULL,
    -- Foreign key to Event.
    "event_id"  VARCHAR(255)  NOT NULL,
    CONSTRAINT "fk_attendees_event_id" FOREIGN KEY ("event_id") REFERENCES "embedded_v1"."events"("name")
);
