// Code generated by protoc-gen-protorm. DO NOT EDIT.
// versions:
// 	protoc-gen-protorm (unknown)
// 	protoc             (unknown)
// source: reserved_words.proto
//
// database: reserved_db
// schema:   public
//
// protorm — https://github.com/oh-tarnished/protorm

package public

// Status is the account state.
type Status string

// Status values as stored in the database.
const (
	StatusUnspecified Status = "unspecified"
	StatusActive      Status = "active"
	StatusClosed      Status = "closed"
)

// Account is forced onto the reserved table name "user" via a table override, with reserved-word columns and a composite UNIQUE index over them.
type Account struct {
	// name: IDENTIFIER → PRIMARY KEY.
	Name string `gorm:"column:name;primaryKey;not null" json:"name"`
	// order is a reserved word; also carries a single-column index.
	Order *string `gorm:"column:order;index" json:"order,omitempty"`
	// select is a reserved word.
	Select *string `gorm:"column:select" json:"select,omitempty"`
	// status exercises a quoted, schema-qualified enum type reference.
	Status Status `gorm:"column:status;not null" json:"status" validate:"required"`
}

func (*Account) TableName() string { return "public.user" }
