// Code generated by protoc-gen-protorm. DO NOT EDIT.
// versions:
// 	protoc-gen-protorm (unknown)
// 	protoc             (unknown)
// source: embedded.proto
//
// database: v1
// schema:   embedded_v1
//
// protorm — https://github.com/oh-tarnished/protorm

package embeddedv1

import (
	"encoding/json"
	"time"
)

// Event exercises nested-message normalization: a singular message field becomes a belongs-to relation, a repeated message field becomes a has-many, while well-known and map fields stay scalar / JSONB.
type Event struct {
	// Resource name; the AIP identifier.
	Name string `gorm:"column:name;primaryKey;not null" json:"name"`
	// Well-known type stays a scalar column, not a relation.
	Created *time.Time `gorm:"column:created" json:"created,omitempty"`
	// Map fields stay JSONB.
	Labels json.RawMessage `gorm:"column:labels" json:"labels,omitempty"`
	// Foreign key to Location.
	LocationID string    `gorm:"column:location_id;not null" json:"location_id" validate:"required"`
	Location   *Location `gorm:"foreignKey:LocationID" json:"location,omitempty"`
	// Foreign key to Location.
	BillingID *string   `gorm:"column:billing_id" json:"billing_id,omitempty"`
	Billing   *Location `gorm:"foreignKey:BillingID" json:"billing,omitempty"`
	// Back-relation: Attendee records that reference this via event_id.
	Attendees []Attendee `gorm:"foreignKey:EventID" json:"attendees,omitempty"`
}

func (*Event) TableName() string { return "embedded_v1.events" }

// Location is reachable from Event and so becomes its own table; its existing `id` field is promoted to the primary key.
type Location struct {
	ID    string  `gorm:"column:id;primaryKey;not null" json:"id"`
	City  string  `gorm:"column:city;not null" json:"city" validate:"required"`
	Venue *string `gorm:"column:venue" json:"venue,omitempty"`
	// Back-relation: Event records that reference this via location_id.
	Events []Event `gorm:"foreignKey:LocationID" json:"events,omitempty"`
	// Back-relation: Event records that reference this via billing_id.
	Events2 []Event `gorm:"foreignKey:BillingID" json:"events2,omitempty"`
}

func (*Location) TableName() string { return "embedded_v1.locations" }

// Attendee carries an IDENTIFIER, so that field is its primary key.
type Attendee struct {
	Name  string `gorm:"column:name;primaryKey;not null" json:"name"`
	Email string `gorm:"column:email;not null" json:"email" validate:"required"`
	// Foreign key to Event.
	EventID string `gorm:"column:event_id;not null" json:"event_id" validate:"required"`
	Event   *Event `gorm:"foreignKey:EventID" json:"event,omitempty"`
}

func (*Attendee) TableName() string { return "embedded_v1.attendees" }
